name: personality-classifier-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow
      - scikit-learn
      - pandas
      - matplotlib
      - seaborn
      - shap
      - joblib
