name: workflow-ci-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - pandas
      - scikit-learn
      - mlflow
      - matplotlib
      - seaborn
      - shap
      - joblib
