name: Workflow CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.7

    - name: Install conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.12
        activate-environment: workflow-ci-env
        environment-file: MLProject/conda.yaml
        use-mamba: true

    - name: Run MLflow project (retrain model)
      run: mlflow run MLProject

    - name: Get latest MLflow run id
      id: mlflow_run
      run: |
        echo "run_id=$(mlflow runs list -n 1 --experiment-name random_forest_personality --output json | jq -r '.[0].run_id')" >> $GITHUB_OUTPUT

    - name: Upload model artifact to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: MLProject/modeling_artifact_path  # sesuaikan path jika sudah punya
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build -t $DOCKER_USERNAME/workflow-ci-model:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker push $DOCKER_USERNAME/workflow-ci-model:latest
