name: CI Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-train:
    name: Set up job
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      - name: Check Env
        run: python --version

      - name: Install dependencies
        run: |
          if [ ! -d "$HOME/miniconda3" ]; then
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p $HOME/miniconda3
            rm miniconda.sh
          fi
          
          export PATH="$HOME/miniconda3/bin:$PATH"

          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn matplotlib seaborn shap joblib

      - name: Run mlflow project
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          mlflow run ./MLProject --experiment-id "2"
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          echo "run_id=mocked_run_id" >> $GITHUB_OUTPUT

      - name: Install Python dependencies
        run: |
          echo "Already installed earlier."

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: downloaded_artifacts/

      - name: Build Docker Model
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/personality-classifier:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/personality-classifier:latest ${{ secrets.DOCKER_USERNAME }}/personality-classifier:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/personality-classifier:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/personality-classifier:${{ github.sha }}
